const html=`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>SokoFlow</title><style>
*{box-sizing:border-box}body{margin:0;font-family:Arial;background:#f7f7f7;color:#222}.top{background:#fff;padding:14px 5%;display:flex;gap:15px;align-items:center;border-bottom:1px solid #ddd}.logo{font-size:28px;font-weight:900}.logo b{color:#f68b1e}.search{flex:1;padding:12px;border:1px solid #ccc;border-radius:5px}.btn{background:#f68b1e;color:white;border:0;border-radius:5px;padding:12px 16px;font-weight:bold}.nav{border:0;background:white;font-weight:bold}.wrap{max-width:1300px;margin:auto;padding:22px 5%}.page{display:none}.active{display:block}.hero{background:#202936;color:white;padding:42px;border-radius:8px}.hero h1{font-size:45px}.hero span{color:#ffad4d}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.card,.panel,.stat{background:white;border:1px solid #e2e2e2;border-radius:8px;padding:15px}.photo{height:150px;background:#edf0f2;display:flex;align-items:center;justify-content:center;overflow:hidden}.photo img{width:100%;height:100%;object-fit:cover}.price{font-size:20px;font-weight:bold;margin:9px 0}.muted{color:#667;font-size:13px}.verified{background:#1877f2;color:#fff;border-radius:50%;padding:2px 5px;font-size:11px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.stat b{display:block;font-size:25px}.form{display:grid;gap:12px;max-width:600px}.form input,.form textarea{padding:12px;border:1px solid #ccc;border-radius:5px}.dash{display:grid;grid-template-columns:200px 1fr;gap:15px}.side{background:#fff;padding:10px}.side button{display:block;width:100%;text-align:left;padding:12px;border:0;background:#fff}.badge{background:#fff3e5;color:#a54e00;padding:5px;border-radius:12px;font-size:12px}.ok{background:#e5f7ea;color:#18723b}.payment{background:#fff3e5;padding:15px;border:1px dashed #e98b20;border-radius:6px}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}@media(max-width:700px){.grid{grid-template-columns:repeat(2,1fr)}.dash{grid-template-columns:1fr}.stats{grid-template-columns:repeat(2,1fr)}.hero h1{font-size:32px}}
</style></head><body>
<header class="top"><div class="logo">SOKO<b>FLOW</b></div><input class="search" id="search" placeholder="Search products, brands and categories" oninput="find()"><button class="nav" onclick="login()">ACCOUNT</button><button class="nav" onclick="go('cart')">CART (<span id="cc">0</span>)</button></header>
<main class="wrap">
<section id="home" class="page active"><div class="hero"><small>MULTI-VENDOR MARKETPLACE</small><h1>Buy from trusted sellers.<br><span>Sell to more customers.</span></h1><p>Discover, compare, trade and coordinate delivery.</p><button class="btn" onclick="go('market')">SHOP NOW</button><div class="payment">PAYMENT INTEGRATION — COMING SOON</div></div><h2>Featured Products</h2><div id="featured" class="grid"></div></section>
<section id="market" class="page"><h1>Marketplace</h1><div id="products" class="grid"></div></section>
<section id="cart" class="page"><h1>Shopping Cart</h1><div id="cart"></div><h2 id="total"></h2><div class="payment">PAYMENTS — COMING SOON</div></section>
<section id="customer" class="page"></section><section id="seller" class="page"></section><section id="delivery" class="page"></section><section id="admin" class="page"></section>
</main>
<script>
let S=JSON.parse(localStorage.getItem('sfpro')||'null')||{p:[{id:1,n:'Wireless Headphones',price:2500,cat:'Electronics',seller:'TechFlow Store',desc:'Clear wireless sound',photo:''},{id:2,n:'Classic Hoodie',price:1800,cat:'Fashion',seller:'Urban Style',desc:'Premium everyday hoodie',photo:''},{id:3,n:'Office Backpack',price:2200,cat:'Accessories',seller:'Daily Essentials',desc:'Work and travel backpack',photo:''},{id:4,n:'Kitchen Set',price:3200,cat:'Home',seller:'HomeCraft',desc:'Kitchen essentials',photo:''}],u:[],cart:[],session:null};
const save=()=>localStorage.setItem('sfpro',JSON.stringify(S));const e=x=>String(x||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function go(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='market')render();if(id==='cart')cart();if(id==='customer')customer();if(id==='seller')seller();if(id==='delivery')delivery();if(id==='admin')admin()}
function card(p){let u=S.u.find(x=>x.business===p.seller);return '<div class="card"><div class="photo">'+(p.photo?'<img src="'+p.photo+'">':e(p.cat))+'</div><b>'+e(p.n)+'</b><div class="price">KSh '+p.price.toLocaleString()+'</div><div class="muted">'+e(p.seller)+(u&&u.verified?' <span class="verified">✓</span>':'')+'</div><button class="btn" onclick="add('+p.id+')">ADD TO CART</button></div>'}
function render(list=S.p){products.innerHTML=list.map(card).join('');featured.innerHTML=S.p.slice(0,4).map(card).join('')}
function add(id){S.cart.push(id);save();cc.textContent=S.cart.length}
function cart(){let a=S.cart.map(id=>S.p.find(p=>p.id===id)).filter(Boolean);document.getElementById('cart').innerHTML=a.length?a.map((p,i)=>'<div class="panel">'+e(p.n)+' — KSh '+p.price+' <button onclick="S.cart.splice('+i+',1);save();cart()">Remove</button></div>').join(''):'Cart is empty';total.textContent='Total: KSh '+a.reduce((s,p)=>s+p.price,0).toLocaleString()}
function find(){go('market');let q=search.value.toLowerCase();render(S.p.filter(p=>(p.n+p.cat+p.seller+p.desc).toLowerCase().includes(q)))}
function login(){let r=prompt('Enter role: customer, seller, delivery, or admin');if(!r)return;if(r==='admin'){let em=prompt('Admin username/email');let pw=prompt('Admin password');if(em==='lesleyengoke22@gmail.com'&&pw==='13739251'){S.session={role:'admin',email:em};save();go('admin')}else alert('Incorrect credentials');return}let email=prompt('Email');let business=prompt(r==='seller'?'Business name':'Name or delivery business');let pw=prompt('Password');if(!email||!business||!pw)return;let u=S.u.find(x=>x.email===email&&x.role===r);if(!u){u={email,business,password:pw,role:r,verified:false};S.u.push(u)}else if(u.password!==pw){alert('Incorrect password');return}S.session={role:r,email};save();go(r)}
function me(){return S.u.find(x=>S.session&&x.email===S.session.email)}
function customer(){document.getElementById('customer').innerHTML='<div class="panel"><h1>Customer Dashboard</h1><div class="stats"><div class="stat">Cart Items<b>'+S.cart.length+'</b></div><div class="stat">Orders<b>0</b></div></div><button class="btn" onclick="go(\\'market\\')">CONTINUE SHOPPING</button></div>'}
function seller(){let u=me(),my=S.p.filter(p=>p.seller===u.business);document.getElementById('seller').innerHTML='<div class="dash"><div class="side"><button onclick="seller()">Dashboard</button><button onclick="addForm()">Add Product</button></div><div class="panel"><h1>Seller Dashboard</h1><p><b>'+e(u.business)+'</b> '+(u.verified?'<span class="verified">✓</span>':'<span class="badge">PENDING VERIFICATION</span>')+'</p><div class="stats"><div class="stat">Products<b>'+my.length+'</b></div><div class="stat">Status<b>'+ (u.verified?'Verified':'Pending')+'</b></div></div><h2>Your Products</h2><div class="grid">'+my.map(card).join('')+'</div></div></div>'}
function addForm(){seller.innerHTML='<div class="panel"><h1>Add Product</h1><div class="form"><input id="pn" placeholder="Product name"><input id="pp" type="number" placeholder="Price"><input id="pc" placeholder="Category"><textarea id="pd" placeholder="Detailed description"></textarea><input id="pf" type="file" accept="image/*"><button class="btn" onclick="addProduct()">SAVE PRODUCT</button></div></div>'}
function addProduct(){let f=pf.files[0],done=photo=>{S.p.unshift({id:Date.now(),n:pn.value,price:Number(pp.value),cat:pc.value,desc:pd.value,seller:me().business,photo:photo||''});save();seller()};if(!pn.value||!pp.value)return alert('Enter name and price');if(f){let r=new FileReader();r.onload=()=>done(r.result);r.readAsDataURL(f)}else done('')}
function delivery(){let u=me();delivery.innerHTML='<div class="panel"><h1>Delivery Dashboard</h1><p><b>'+e(u.business)+'</b> '+(u.verified?'<span class="verified">✓</span>':'<span class="badge">PENDING VERIFICATION</span>')+'</p><div class="stats"><div class="stat">Assigned<b>0</b></div><div class="stat">Completed<b>0</b></div></div></div>'}
function admin(){let rows=r=>S.u.filter(u=>u.role===r).map(u=>'<tr><td>'+e(u.business)+(u.verified?' <span class="verified">✓</span>':'')+'</td><td>'+e(u.email)+'</td><td><span class="badge '+(u.verified?'ok':'')+'">'+(u.verified?'VERIFIED':'PENDING')+'</span></td><td><button class="btn" onclick="verify(\\''+u.email+'\\')">'+(u.verified?'REMOVE':'APPROVE')+'</button></td></tr>').join('')||'<tr><td colspan="4">No applications</td></tr>';admin.innerHTML='<div class="panel"><h1>Administrator Dashboard</h1><div class="stats"><div class="stat">Products<b>'+S.p.length+'</b></div><div class="stat">Sellers<b>'+S.u.filter(u=>u.role==='seller').length+'</b></div><div class="stat">Delivery<b>'+S.u.filter(u=>u.role==='delivery').length+'</b></div></div><h2>Seller Verification</h2><table><tr><th>Business</th><th>Email</th><th>Status</th><th>Action</th></tr>'+rows('seller')+'</table><h2>Delivery Partner Verification</h2><table><tr><th>Business</th><th>Email</th><th>Status</th><th>Action</th></tr>'+rows('delivery')+'</table></div>'}
function verify(email){let u=S.u.find(x=>x.email===email);u.verified=!u.verified;save();admin()}
cc.textContent=S.cart.length;render();
</script></body></html>`;
export default {async fetch(){return new Response(html,{headers:{'content-type':'text/html;charset=UTF-8'}})}};
